### ISSUE TITLE
Rewriting Python program in Fortran.

### ISSUE THREAD

**Issue by mjaykr** [LightForm-group/KWN-deformation#26]
I observe that Python is being used just to read the input file and create another input.dat which is an array of numbers. I purpose to rewrite it in fortran so that we can ignore the need of extra programming language. What is your opinion?

**Comment by douglowe** [comment]
I would suggest that we use a namelist file for the inputs - this wouldn't require a preprocessor program, as it would be a similar layout to the existing input.yaml file.

**Comment by mjaykr** [comment]
I have wrote the namelist file and now slightly we need to rewrite the main program.

**Comment by mjaykr** [comment]
> 

I have wrote a script to read the namelist file, Please find it here
https://github.com/LightForm-group/KWN-deformation/blob/mjaykr-input-namelist/read_input.f90
I hope it will be helpful.

**Comment by douglowe** [comment]
Great :)

However - fortran can read namelist files natively, without requiring the formatting commands. For example:
```
integer :: var1, var2, var3
namelist/myinputs/var1, var2, var3
read (5, nml=myinputs)
```
will read the record:
```
&myinputs var1=4, var2=3, var3=7 /
```
and will also read this record, because record order is no longer important:
```
&myinputs var3=2, var1=3, var2=7 /
```
Note that `nml` replaces `fmt` as the specifier in the `read` command.

One issue I'm not sure about is how namelists and type declarations will interact. So I think that we would have to read the namelist into standard variables, then copy that information into the type'd arrays. Also, if we have information in the namelist file that is used to allocate arrays, then that would have to be read and processed before we can fill the allocated arrays. But we can get around that by reading into a large fixed array, then copying the data into the allocated array after allocation.

I won't be adding any more code to the `module_refactor` branch until Friday. @mjaykr - do you want to try adapting the `read_configuration` subroutine in the `src/KWN_io.f90` file to read a namelist file in the manner described above? Then I'll give it a look over on Friday for you.

**Comment by douglowe** [comment]
Also note, a namelist file can contain multiple namelists - a good example of this is the WRF namelist, see this example: https://github.com/wrf-model/WRF/blob/master/test/em_b_wave/namelist.input

It might be useful for future users for the namelist to be split into logical groupings - physical parameters, material properties, run controls, etc.

**Comment by douglowe** [comment]
hi @mjaykr - I've incorporated a namelist file into my module_refactor code - so this task will be (mostly) covered by PR https://github.com/LightForm-group/KWN-deformation/pull/27
